name: PronghornMinecraftPlugin
main: com.ociweb.device.testApps.PronghornMinecraftPlugin
version: 1.0.0
author: alexherriott1
commands:
  generatepi:
    description: This generates the mock Pi
    usage: /<generatepi> [player]
    permission: PronghornMinecraftPlugin.generatepi
    permission-message: You don't have <permission>